// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pDsONctoQ9N_6zLE0aYLgD5ciKwhbBA',
    appId: '1:879454478437:web:ee1390cf2f3df838c1668c',
    messagingSenderId: '879454478437',
    projectId: 'eventbuddy-76556',
    authDomain: 'eventbuddy-76556.firebaseapp.com',
    storageBucket: 'eventbuddy-76556.firebasestorage.app',
    measurementId: 'G-5MD5H3T2RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYN8-2BCjPndYyzSPdOWpMzmoyk_Uhbf0',
    appId: '1:879454478437:android:ba681dc8183a4a51c1668c',
    messagingSenderId: '879454478437',
    projectId: 'eventbuddy-76556',
    storageBucket: 'eventbuddy-76556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANkaMz85yqJXMzNX8NaiBH0t8kTOD4_s',
    appId: '1:879454478437:ios:100e2c124b7e9336c1668c',
    messagingSenderId: '879454478437',
    projectId: 'eventbuddy-76556',
    storageBucket: 'eventbuddy-76556.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANkaMz85yqJXMzNX8NaiBH0t8kTOD4_s',
    appId: '1:879454478437:ios:100e2c124b7e9336c1668c',
    messagingSenderId: '879454478437',
    projectId: 'eventbuddy-76556',
    storageBucket: 'eventbuddy-76556.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1pDsONctoQ9N_6zLE0aYLgD5ciKwhbBA',
    appId: '1:879454478437:web:aed3f7c1b25ad20cc1668c',
    messagingSenderId: '879454478437',
    projectId: 'eventbuddy-76556',
    authDomain: 'eventbuddy-76556.firebaseapp.com',
    storageBucket: 'eventbuddy-76556.firebasestorage.app',
    measurementId: 'G-0T4M2Z2WV0',
  );
}
